// <auto-generated> GENERATED FILE - do not edit. Run npm run generate:contract. </auto-generated>
namespace PowerBIModelingService.RpcHost;

internal static class GeneratedScorePanelContract
{
    internal const int ProtocolVersion = 1;
    internal const int SchemaVersion = 1;
    internal static readonly IReadOnlySet<string> MutationOperations = new HashSet<string>(StringComparer.Ordinal) { "preview", "apply", "rollback" };
}
